# Credit Card Fraud Detection::

Download dataset from this link:

https://www.kaggle.com/mlg-ulb/creditcardfraud

# Description about dataset::

The datasets contains transactions made by credit cards in September 2013 by european cardholders.
This dataset presents transactions that occurred in two days, where we have 492 frauds out of 284,807 transactions. The dataset is highly unbalanced, the positive class (frauds) account for 0.172% of all transactions.

It contains only numerical input variables which are the result of a PCA transformation. Unfortunately, due to confidentiality issues, we cannot provide the original features and more background information about the data. Features V1, V2, … V28 are the principal components obtained with PCA, the only features which have not been transformed with PCA are 'Time' and 'Amount'. Feature 'Time' contains the seconds elapsed between each transaction and the first transaction in the dataset. The feature 'Amount' is the transaction Amount, this feature can be used for example-dependant cost-senstive learning. 


### Feature 'Class' is the response variable and it takes value 1 in case of fraud and 0 otherwise.

# WORKFLOW :

1.Load Data

2.Check Missing Values ( If Exist ; Fill each record with mean of its feature )

3.Standardized the Input Variables. 

4.Split into 50% Training(Samples,Labels) , 30% Test(Samples,Labels) and 20% Validation Data(Samples,Labels).

5.Model : input Layer (No. of features ), 3 hidden layers including 10,8,6 unit & Output Layer with activation function relu/tanh (check by experiment).

6.Compilation Step (Note : Its a Binary problem , select loss , metrics according to it)

7.Train the Model with Epochs (100).

8.If the model gets overfit tune your model by changing the units , No. of layers , epochs , add dropout layer or add Regularizer according to the need .

9.Prediction should be > 92%
10.Evaluation Step
11Prediction


# Task::

## Identify fraudulent credit card transactions.

In [106]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
%matplotlib inline

from tensorflow.keras import models
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential # Sequential/Functional Api
from tensorflow.keras.layers import Dense # type of layer
from tensorflow.keras import regularizers
from keras.regularizers import l1
from keras.regularizers import l2

import tensorflow_docs as tfdocs
import tensorflow_docs.plots
import tensorflow_docs.modeling


In [107]:
data = pd.read_csv('creditcard.csv')
data.describe().T

count          mean           std         min           25%  \
Time    284807.0  9.481386e+04  47488.145955    0.000000  54201.500000   
V1      284807.0  3.919560e-15      1.958696  -56.407510     -0.920373   
V2      284807.0  5.688174e-16      1.651309  -72.715728     -0.598550   
V3      284807.0 -8.769071e-15      1.516255  -48.325589     -0.890365   
V4      284807.0  2.782312e-15      1.415869   -5.683171     -0.848640   
V5      284807.0 -1.552563e-15      1.380247 -113.743307     -0.691597   
V6      284807.0  2.010663e-15      1.332271  -26.160506     -0.768296   
V7      284807.0 -1.694249e-15      1.237094  -43.557242     -0.554076   
V8      284807.0 -1.927028e-16      1.194353  -73.216718     -0.208630   
V9      284807.0 -3.137024e-15      1.098632  -13.434066     -0.643098   
V10     284807.0  1.768627e-15      1.088850  -24.588262     -0.535426   
V11     284807.0  9.170318e-16      1.020713   -4.797473     -0.762494   
V12     284807.0 -1.810658e-15      0.999201  -18.683715     -0.405571   
V13     284807.0  1.693438e-15      0.995274   -5.791881     -0.648539   
V14     284807.0  1.479045e-15      0.958596  -19.214325     -0.425574   
V15     284807.0  3.482336e-15      0.915316   -4.498945     -0.582884   
V16     284807.0  1.392007e-15      0.876253  -14.129855     -0.468037   
V17     284807.0 -7.528491e-16      0.849337  -25.162799     -0.483748   
V18     284807.0  4.328772e-16      0.838176   -9.498746     -0.498850   
V19     284807.0  9.049732e-16      0.814041   -7.213527     -0.456299   
V20     284807.0  5.085503e-16      0.770925  -54.497720     -0.211721   
V21     284807.0  1.537294e-16      0.734524  -34.830382     -0.228395   
V22     284807.0  7.959909e-16      0.725702  -10.933144     -0.542350   
V23     284807.0  5.367590e-16      0.624460  -44.807735     -0.161846   
V24     284807.0  4.458112e-15      0.605647   -2.836627     -0.354586   
V25     284807.0  1.453003e-15      0.521278  -10.295397     -0.317145   
V26     284807.0  1.699104e-15      0.482227   -2.604551     -0.326984   
V27     284807.0 -3.660161e-16      0.403632  -22.565679     -0.070840   
V28     284807.0 -1.206049e-16      0.330083  -15.430084     -0.052960   
Amount  284807.0  8.834962e+01    250.120109    0.000000      5.600000   
Class   284807.0  1.727486e-03      0.041527    0.000000      0.000000   

                 50%            75%            max  
Time    84692.000000  139320.500000  172792.000000  
V1          0.018109       1.315642       2.454930  
V2          0.065486       0.803724      22.057729  
V3          0.179846       1.027196       9.382558  
V4         -0.019847       0.743341      16.875344  
V5         -0.054336       0.611926      34.801666  
V6         -0.274187       0.398565      73.301626  
V7          0.040103       0.570436     120.589494  
V8          0.022358       0.327346      20.007208  
V9         -0.051429       0.597139      15.594995  
V10        -0.092917       0.453923      23.745136  
V11        -0.032757       0.739593      12.018913  
V12         0.140033       0.618238       7.848392  
V13        -0.013568       0.662505       7.126883  
V14         0.050601       0.493150      10.526766  
V15         0.048072       0.648821       8.877742  
V16         0.066413       0.523296      17.315112  
V17        -0.065676       0.399675       9.253526  
V18        -0.003636       0.500807       5.041069  
V19         0.003735       0.458949       5.591971  
V20        -0.062481       0.133041      39.420904  
V21        -0.029450       0.186377      27.202839  
V22         0.006782       0.528554      10.503090  
V23        -0.011193       0.147642      22.528412  
V24         0.040976       0.439527       4.584549  
V25         0.016594       0.350716       7.519589  
V26        -0.052139       0.240952       3.517346  
V27         0.001342       0.091045      31.612198  
V28         0.011244       0.078280      33.847808  
Amount     22.000000      77.165000   25691.160000  

In [108]:
data.shape

(284807, 31)

In [109]:
data.isna().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [110]:
data = data.drop(['Time'],axis=1)

In [111]:
train_data = data.sample(frac=0.7, random_state=0) # will reserve 20% for validation during training
test_data = data.drop(train_data.index)

In [112]:
# separating the target value, or “label”, from the features.
train_labels = train_data.pop('Class')
test_labels = test_data.pop('Class')

In [113]:
mean = train_data.mean(axis=0)
train_data -= mean
std = train_data.std(axis=0)
train_data /= std

test_data -= mean
test_data /= std

In [114]:
def build_model():
    from tensorflow import keras
    model = models.Sequential()
    model.add(layers.Dense(128, activation='relu',
                           kernel_initializer = 'uniform',input_dim = 29))
    model.add(layers.Dropout(0.2))
    model.add(layers.Dense(64, kernel_initializer = 'uniform', activation='relu'))
    model.add(layers.Dropout(0.2))
    model.add(layers.Dense(32, kernel_initializer = 'uniform', activation='relu'))
    model.add(layers.Dropout(0.2))
    model.add(layers.Dense(32, kernel_initializer = 'uniform', activation='relu'))
    model.add(layers.Dropout(0.2))
    model.add(layers.Dense(16, kernel_initializer = 'uniform', activation='relu'))    
    model.add(layers.Dropout(0.2))
    model.add(layers.Dense(1, activation='sigmoid'))
    model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return model

In [115]:
model = build_model()
model.summary()

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_36 (Dense)             (None, 128)               3840      
_________________________________________________________________
dropout_30 (Dropout)         (None, 128)               0         
_________________________________________________________________
dense_37 (Dense)             (None, 64)                8256      
_________________________________________________________________
dropout_31 (Dropout)         (None, 64)                0         
_________________________________________________________________
dense_38 (Dense)             (None, 32)                2080      
_________________________________________________________________
dropout_32 (Dropout)         (None, 32)                0         
_________________________________________________________________
dense_39 (Dense)             (None, 32)               

In [117]:
EPOCHS = 100

history = model.fit(
  train_data, train_labels,
  epochs=EPOCHS, validation_split = 0.2, verbose=0,
  callbacks=[tfdocs.modeling.EpochDots()])


Epoch: 0, acc:0.9982,  loss:0.0102,  val_acc:0.9986,  val_loss:0.0041,  
....................................................................................................

In [120]:
[loss, mae] = model.evaluate(test_data, test_labels, verbose=1)

test_predictions = model.predict(test_data)

frauds = np.where(test_labels[:]==1)[0]
print(frauds[0:5])
print(test_labels.values[frauds[0:5]])
print(np.around(test_predictions[frauds[0:5]]))

85442/85442 [==============================] - 3s 32us/sample - loss: 0.0275 - acc: 0.9993
[1813 1879 1882 1883 1922]
[1 1 1 1 1]
[[0.]
 [1.]
 [1.]
 [1.]
 [1.]]
