# Assignment: Ionosphere Data Problem

### Dataset Description: 

This radar data was collected by a system in Goose Bay, Labrador. This system consists of a phased array of 16 high-frequency antennas with a total transmitted power on the order of 6.4 kilowatts. See the paper for more details. The targets were free electrons in the ionosphere. "Good" radar returns are those showing evidence of some type of structure in the ionosphere. "Bad" returns are those that do not; their signals pass through the ionosphere.

Received signals were processed using an autocorrelation function whose arguments are the time of a pulse and the pulse number. There were 17 pulse numbers for the Goose Bay system. Instances in this databse are described by 2 attributes per pulse number, corresponding to the complex values returned by the function resulting from the complex electromagnetic signal.

### Attribute Information:

- All 34 are continuous
- The 35th attribute is either "good" or "bad" according to the definition summarized above. This is a binary classification task.

 <br><br>

<table border="1"  cellpadding="6">
	<tbody>
        <tr>
		<td bgcolor="#DDEEFF"><p class="normal"><b>Data Set Characteristics:&nbsp;&nbsp;</b></p></td>
		<td><p class="normal">Multivariate</p></td>
		<td bgcolor="#DDEEFF"><p class="normal"><b>Number of Instances:</b></p></td>
		<td><p class="normal">351</p></td>
		<td bgcolor="#DDEEFF"><p class="normal"><b>Area:</b></p></td>
		<td><p class="normal">Physical</p></td>
        </tr>
     </tbody>
    </table>
<table border="1" cellpadding="6">
    <tbody>
        <tr>
            <td bgcolor="#DDEEFF"><p class="normal"><b>Attribute Characteristics:</b></p></td>
            <td><p class="normal">Integer,Real</p></td>
            <td bgcolor="#DDEEFF"><p class="normal"><b>Number of Attributes:</b></p></td>
            <td><p class="normal">34</p></td>
            <td bgcolor="#DDEEFF"><p class="normal"><b>Date Donated</b></p></td>
            <td><p class="normal">N/A</p></td>
        </tr>
     </tbody>
    </table>
<table border="1" cellpadding="6">	
    <tbody>
    <tr>
		<td bgcolor="#DDEEFF"><p class="normal"><b>Associated Tasks:</b></p></td>
		<td><p class="normal">Classification</p></td>
		<td bgcolor="#DDEEFF"><p class="normal"><b>Missing Values?</b></p></td>
		<td><p class="normal">N/A</p></td>
		<td bgcolor="#DDEEFF"><p class="normal"><b>Number of Web Hits:</b></p></td>
		<td><p class="normal">N/A</p></td>
	</tr>
    </tbody>
    </table>

### WORKFLOW :
- Load Data
- Check Missing Values ( If Exist ; Fill each record with mean of its feature ) or any usless column.
- Shuffle the data if needed.
- Standardized the Input Variables. **Hint**: Centeralized the data
- Split into 60 and 40 ratio.
- Encode labels.
- Model : 1 hidden layers including 16 unit.
- Compilation Step (Note : Its a Binary problem , select loss , metrics according to it)
- Train the Model with Epochs (100).
- If the model gets overfit tune your model by changing the units , No. of layers , epochs , add dropout layer or add Regularizer according to the need .
- Prediction should be > **92%**
- Evaluation Step
- Prediction


# Load Data:
[Click Here to Download DataSet](https://github.com/ramsha275/ML_Datasets/blob/main/ionosphere_data.csv)

In [72]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
%matplotlib inline

from tensorflow.keras import models
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential # Sequential/Functional Api
from tensorflow.keras.layers import Dense # type of layer
from tensorflow.keras import regularizers
from keras.regularizers import l1
from keras.regularizers import l2

import tensorflow_docs as tfdocs
import tensorflow_docs.plots
import tensorflow_docs.modeling

In [73]:
data = pd.read_csv('ionosphere_data.csv')
data.describe()

feature1  feature2    feature3    feature4    feature5    feature6  \
count  351.000000     351.0  351.000000  351.000000  351.000000  351.000000   
mean     0.891738       0.0    0.641342    0.044372    0.601068    0.115889   
std      0.311155       0.0    0.497708    0.441435    0.519862    0.460810   
min      0.000000       0.0   -1.000000   -1.000000   -1.000000   -1.000000   
25%      1.000000       0.0    0.472135   -0.064735    0.412660   -0.024795   
50%      1.000000       0.0    0.871110    0.016310    0.809200    0.022800   
75%      1.000000       0.0    1.000000    0.194185    1.000000    0.334655   
max      1.000000       0.0    1.000000    1.000000    1.000000    1.000000   

         feature7    feature8    feature9   feature10  ...   feature25  \
count  351.000000  351.000000  351.000000  351.000000  ...  351.000000   
mean     0.550095    0.119360    0.511848    0.181345  ...    0.396135   
std      0.492654    0.520750    0.507066    0.483851  ...    0.578451   
min     -1.000000   -1.000000   -1.000000   -1.000000  ...   -1.000000   
25%      0.211310   -0.054840    0.087110   -0.048075  ...    0.000000   
50%      0.728730    0.014710    0.684210    0.018290  ...    0.553890   
75%      0.969240    0.445675    0.953240    0.534195  ...    0.905240   
max      1.000000    1.000000    1.000000    1.000000  ...    1.000000   

        feature26   feature27   feature28   feature29   feature30   feature31  \
count  351.000000  351.000000  351.000000  351.000000  351.000000  351.000000   
mean    -0.071187    0.541641   -0.069538    0.378445   -0.027907    0.352514   
std      0.508495    0.516205    0.550025    0.575886    0.507974    0.571483   
min     -1.000000   -1.000000   -1.000000   -1.000000   -1.000000   -1.000000   
25%     -0.332390    0.286435   -0.443165    0.000000   -0.236885    0.000000   
50%     -0.015050    0.708240   -0.017690    0.496640    0.000000    0.442770   
75%      0.156765    0.999945    0.153535    0.883465    0.154075    0.857620   
max      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000   

        feature32   feature33   feature34  
count  351.000000  351.000000  351.000000  
mean    -0.003794    0.349364    0.014480  
std      0.513574    0.522663    0.468337  
min     -1.000000   -1.000000   -1.000000  
25%     -0.242595    0.000000   -0.165350  
50%      0.000000    0.409560    0.000000  
75%      0.200120    0.813765    0.171660  
max      1.000000    1.000000    1.000000  

[8 rows x 34 columns]

In [74]:
data.shape

(351, 35)

In [75]:
data.describe(include='object')

label
count    351
unique     2
top        g
freq     225

In [76]:
data["label"].value_counts()

g    225
b    126
Name: label, dtype: int64

In [77]:
data["label_binary"] = np.where(data["label"]=='g', 1, 0)
data = data.drop(['label'],axis=1)

In [78]:
data.sample(5)

feature1  feature2  feature3  feature4  feature5  feature6  feature7  \
23          0         0  -1.00000   1.00000   0.00000   0.00000   0.00000   
271         1         0   0.47938  -0.12371   0.42784  -0.12371   0.70103   
135         1         0   0.89706   0.38235   0.91176   0.37500   0.74265   
50          1         0   0.84134  -0.18362   0.43644   0.02919   0.93421   
100         1         0   1.00000  -1.00000   0.00000   0.00000   0.77941   

     feature8  feature9  feature10  ...  feature26  feature27  feature28  \
23    0.00000  -1.00000    1.00000  ...   -1.00000    1.00000   -1.00000   
271  -0.39175   0.73196    0.07216  ...    0.19588    0.53396   -0.12447   
135   0.67647   0.45588    0.77941  ...   -0.12500   -0.67925   -0.24131   
50   -0.00267   0.87947    0.13795  ...   -0.02778    0.93358   -0.01158   
100  -0.99265   0.80882    0.55147  ...   -1.00000   -1.00000   -1.00000   

     feature29  feature30  feature31  feature32  feature33  feature34  \
23     1.00000    1.00000   -1.00000    1.00000    0.00000    0.00000   
271    0.15464   -0.26289    0.47423    0.04124    0.45361   -0.51546   
135   -0.55147   -0.42647   -0.44118   -0.50735   -0.28676   -0.56618   
50     0.61582   -0.32298    0.84463   -0.25706    0.93323   -0.01425   
100    1.00000   -1.00000    1.00000   -1.00000    0.00000    0.00000   

     label_binary  
23              0  
271             1  
135             1  
50              1  
100             0  

[5 rows x 35 columns]

In [79]:
data.isna().sum()

feature1        0
feature2        0
feature3        0
feature4        0
feature5        0
feature6        0
feature7        0
feature8        0
feature9        0
feature10       0
feature11       0
feature12       0
feature13       0
feature14       0
feature15       0
feature16       0
feature17       0
feature18       0
feature19       0
feature20       0
feature21       0
feature22       0
feature23       0
feature24       0
feature25       0
feature26       0
feature27       0
feature28       0
feature29       0
feature30       0
feature31       0
feature32       0
feature33       0
feature34       0
label_binary    0
dtype: int64

In [80]:
train_data = data.sample(frac=0.6, random_state=0) # will reserve 20% for validation during training
test_data = data.drop(train_data.index)

In [81]:
# separating the target value, or “label”, from the features.
train_labels = train_data.pop('label_binary')
test_labels = test_data.pop('label_binary')

In [82]:
mean = train_data.mean(axis=0)
train_data -= mean
std = train_data.std(axis=0)
train_data /= std

test_data -= mean
test_data /= std

train_data.head()
train_data.drop('feature2',axis=1, inplace=True)
test_data.drop('feature2',axis=1, inplace=True)

In [120]:
def build_model():
    from tensorflow import keras
    model = models.Sequential()
    model.add(layers.Dense(128, activation='relu',
                           kernel_regularizer=regularizers.l1_l2(l1=0.001,l2=0.001),input_dim = 33))
    model.add(layers.Dropout(0.2))
    model.add(layers.Dense(128, kernel_regularizer=regularizers.l1_l2(l1=0.001,l2=0.001), activation='relu'))
    model.add(layers.Dropout(0.2))
    model.add(layers.Dense(64, kernel_regularizer=regularizers.l1_l2(l1=0.001,l2=0.001), activation='relu'))
    model.add(layers.Dropout(0.2))
    model.add(layers.Dense(32, kernel_regularizer=regularizers.l1_l2(l1=0.001,l2=0.001), activation='relu'))
    model.add(layers.Dropout(0.2))
    model.add(layers.Dense(16, kernel_regularizer=regularizers.l1_l2(l1=0.001,l2=0.001), activation='relu'))    
    model.add(layers.Dropout(0.2))
    model.add(layers.Dense(1, activation='sigmoid'))
    model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return model

In [121]:
model = build_model()
model.summary()

Model: "sequential_15"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_65 (Dense)             (None, 128)               4352      
_________________________________________________________________
dropout_41 (Dropout)         (None, 128)               0         
_________________________________________________________________
dense_66 (Dense)             (None, 128)               16512     
_________________________________________________________________
dropout_42 (Dropout)         (None, 128)               0         
_________________________________________________________________
dense_67 (Dense)             (None, 64)                8256      
_________________________________________________________________
dropout_43 (Dropout)         (None, 64)                0         
_________________________________________________________________
dense_68 (Dense)             (None, 32)              

In [122]:
example_batch = train_data[:10]
example_result = model.predict(example_batch)
example_result

array([[0.53337324],
       [0.50198084],
       [0.47793365],
       [0.5074225 ],
       [0.52250266],
       [0.51841193],
       [0.5592905 ],
       [0.52789414],
       [0.52212805],
       [0.51942414]], dtype=float32)

In [123]:
EPOCHS = 100

history = model.fit(
  train_data, train_labels,
  epochs=EPOCHS, validation_split = 0.2, verbose=1,
  callbacks=[tfdocs.modeling.EpochDots()])

Train on 168 samples, validate on 43 samples
Epoch 1/100
 32/168 [====>.........................] - ETA: 1s - loss: 3.7270 - acc: 0.5625
Epoch: 0, acc:0.5833,  loss:3.6923,  val_acc:0.6279,  val_loss:3.6325,  
168/168 [==============================] - 1s 5ms/sample - loss: 3.6923 - acc: 0.5833 - val_loss: 3.6325 - val_acc: 0.6279
Epoch 2/100
168/168 [==============================] - 0s 202us/sample - loss: 3.6022 - acc: 0.6190 - val_loss: 3.5241 - val_acc: 0.7442
Epoch 3/100
168/168 [==============================] - 0s 271us/sample - loss: 3.5065 - acc: 0.7083 - val_loss: 3.4114 - val_acc: 0.8140
Epoch 4/100
168/168 [==============================] - 0s 267us/sample - loss: 3.3804 - acc: 0.7202 - val_loss: 3.2917 - val_acc: 0.8372
Epoch 5/100
168/168 [==============================] - 0s 291us/sample - loss: 3.2635 - acc: 0.7917 - val_loss: 3.1715 - val_acc: 0.8372
Epoch 6/100
168/168 [==============================] - 0s 306us/sample - loss: 3.1070 - acc: 0.8571 - val_loss: 3.0530 

168/168 [==============================] - 0s 237us/sample - loss: 0.7244 - acc: 0.9940 - val_loss: 0.8571 - val_acc: 0.9302
Epoch 59/100
168/168 [==============================] - 0s 214us/sample - loss: 0.7283 - acc: 0.9821 - val_loss: 0.8471 - val_acc: 0.9302
Epoch 60/100
168/168 [==============================] - 0s 261us/sample - loss: 0.7124 - acc: 0.9762 - val_loss: 0.8310 - val_acc: 0.9302
Epoch 61/100
168/168 [==============================] - 0s 193us/sample - loss: 0.6994 - acc: 0.9881 - val_loss: 0.8565 - val_acc: 0.9302
Epoch 62/100
168/168 [==============================] - 0s 232us/sample - loss: 0.7063 - acc: 0.9643 - val_loss: 0.9466 - val_acc: 0.8605
Epoch 63/100
168/168 [==============================] - 0s 214us/sample - loss: 0.6904 - acc: 0.9762 - val_loss: 0.7898 - val_acc: 0.9302
Epoch 64/100
168/168 [==============================] - 0s 235us/sample - loss: 0.6588 - acc: 0.9821 - val_loss: 0.7871 - val_acc: 0.9302
Epoch 65/100
168/168 [=========================

In [124]:
[loss, mae] = model.evaluate(test_data, test_labels, verbose=1)

test_predictions = model.predict(test_data)

frauds = np.where(test_labels[:]==1)[0]
print(frauds[0:5])
print(test_labels.values[frauds[0:5]])
print(np.around(test_predictions[frauds[0:5]]))

140/140 [==============================] - 0s 85us/sample - loss: 0.5246 - acc: 0.9357
[ 0  1  4  7 10]
[1 1 1 1 1]
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]
